name = "mail-shudao"
main = "src/index.js"
compatibility_date = "2026-03-01"
assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "mail_db"
database_id = "a7fa2821-79a8-4e50-bc38-ccc3281b0107"

[vars]
ALLOWED_DOMAINS = "shudao.ai"
DOMAINS = "shudao.ai"

routes = [
  { pattern = "mail.shudao.ai", custom_domain = true }
]