name = "mail-shudao"
main = "src/index.js"
compatibility_date = "2026-03-01"

# 将 public 目录下的静态网页托管出去
assets = { directory = "./public" }

# 绑定 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "mail_db"
database_id = "a7fa2821-79a8-4e50-bc38-ccc3281b0107"

[vars]
ALLOWED_DOMAINS = "shudao.ai"
DOMAINS = "shudao.ai"

send_email = [
  { name = "SEND_EMAIL" }
]